export interface SkillVersion {
  versao: string; // e.g., "v1.0", "v1.1", "v2.0"
  data: string; // ISO date string
  conteudo_do_prompt: string;
  changelog?: string;
  autoGenerated?: boolean;
}

export interface AutoSaveConfig {
  enabled: boolean;
  intervalMinutes: number; // default 2
  autoVersionEditsThreshold: number; // default 5 edits
  autoVersionMinutesThreshold: number; // default 30 minutes
}

export interface Skill {
  id: string;
  titulo: string;
  descricao: string;
  link_github?: string;
  tags: string[];
  versoes: SkillVersion[];
  assets?: string[]; // Attached files/images saved in assets/ folder
  relativePath?: string; // Path relative to /skills root directory
  filename?: string;
}

export interface FileTreeNode {
  id: string;
  name: string;
  path: string;
  relativePath: string;
  type: "folder" | "file";
  children?: FileTreeNode[];
  data?: Skill;
}

export interface GitCommit {
  hash: string;
  message: string;
  author: string;
  date: string;
  status: "synced" | "pending" | "conflict";
}

export interface GitConfig {
  repoUrl: string;
  branch: string;
  authorName: string;
  authorEmail: string;
  autoSync: boolean;
  autoSyncIntervalMinutes?: number; // e.g. 60 (1 hour), 30, 15, 120
  lastSyncTime?: string;
  commits: GitCommit[];
}

export type ThemeMode = "light" | "dark" | "system";

export type AccentColor = "indigo" | "violet" | "emerald" | "amber" | "rose" | "cyan" | "slate";

export interface ThemeConfig {
  mode: ThemeMode;
  accent: AccentColor;
  storagePath: string;
}

export interface SearchFilter {
  query: string;
  selectedTag?: string;
  selectedFolder?: string;
}
